#version: "3.8"
#
#services:
#  postgres:
#    image: postgres:17
#    container_name: loan_calculator_db
#    environment:
#      POSTGRES_DB: loan_calculator
#      POSTGRES_USER: andjela_loan
#      POSTGRES_PASSWORD: andjela_loan_pass
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
#volumes:
#  pgdata:
